### PR TITLE
Add simple moving average market strategy

### PR DESCRIPTION
**Pull request by andrebreis**
also fix other strategies' behaviour when they have more btc than needed

Needs tests - done :heavy_check_mark: 

Needs discussion: Should we assume market liquidity? So if a bid is created at last market price is it good enough to assume that it will be matched or should we check on the next iteration? - iteration checks if last iteration bid was fullfilled (and takes into account if it was fully or partially) :heavy_check_mark:

### CODE REVIEW

**Comment by MattSkala** [comment]
I think it looks good overall.

1) I would just add some documenting comments, briefly describe what each method does, and add a high-level description of the strategy (which can be later copy-pasted to README as well). It would considerably help future maintainers to understand the code.

2) Currently, `update_offer` never gets called. Initially, `time_accumulated` is `0` and updated to `5` when the strategy is applied. But in `sell_reputation`, if `last_price < moving_average`, then `self.time_accumulated <= MAX_ACCUMULATION_TIME` and return is executed.

3) `time_change` could be just a local variable, as it is only used in a single place.

4) If you want to record the market transaction history, you should probably enable `record_transactions` option in `plebnet_plugin.py`.

**Comment by andrebreis** [comment]
> I would just add some documenting comments, briefly describe what each method does, and add a high-level description of the strategy (which can be later copy-pasted to README as well). It would considerably help future maintainers to understand the code.

The high level strategy is in the Market Strategy issue, maybe just like it there? I'll add the method description

> 2. Currently, `update_offer` never gets called. Initially, `time_accumulated` is `0` and updated to `5` when the strategy is applied. But in `sell_reputation`, if `last_price < moving_average`, then `self.time_accumulated <= MAX_ACCUMULATION_TIME` and return is executed.
> 3. `time_change` could be just a local variable, as it is only used in a single place.

This was a mistake. `time_accumulated` is read from last iteration (and then is incremented for the 5 minutes passed during checks). `time_change` is the decrement that the last bid caused on the time accumulated. It is (now) saved to file and read in the next iteration, incrementing time equivalent to the part of the bid that wasn't fulfilled.

**Comment by MattSkala** [comment]
Looks good. One concern though. Since it tries to update an offer every 5 minutes, it could try to place a very small offer. However, currently the minimum amount required for creating an order on the market is 1mBTC, otherwise the API request for placing the order fails (https://github.com/Tribler/tribler/blob/9d5e2a1cf9995113954216d626c347a8ce726474/Tribler/Core/Modules/wallet/btc_wallet.py#L185). Does the strategy work correctly even with this restriction?

**Comment by andrebreis** [comment]
Very good point. That will depend completely on the price of MB. 

So we might want to be a little more conservative and maybe change the offer size for the strategy... For tokens produced in 1 day maybe?

**Comment by MattSkala** [comment]
Yes, it probably makes sense to be more conservative and place orders with larger amounts of tokens.

**Pull request merged**
