### PR TITLE
Intrudcing probabilistic qtables

### PR DESCRIPTION
**Pull request by rpytel1**
This changes introduces probabilisitic choosing of offers according to exponential distribution.

### CODE REVIEW

**Comment by rpytel1** [comment]
Merge?

**Comment by MattSkala** [comment]
1. If I understand the calculations in `choose_option` correctly, it randomly selects options from exponential distribution with the average value of `4/3` in the first generation and converges to the distribution with the average value of `1`. So the QTable will be always probabilistic even after many generations and is not converging to a deterministic algorithm. That's probably fine, but I'd mention in a comment how it works so no one has to reverse-engineer the code.

2. I know this is not related, but can you update `calculate_measure` so it gives more weight on price? Currently it almost always chooses routerhosting_64 or routerhosting_32, which are the most expensive options.

**Comment by MattSkala** [comment]
It's still choosing the same options as before. I found out the problem is not in the measure itself, but that it is always selecting the option with the lowest (instead of highest) measure.

**Comment by rpytel1** [comment]
> It's still choosing the same options as before. I found out the problem is not in the measure itself, but that it is always selecting the option with the lowest (instead of highest) measure.

Thank for check! I fixed it :)

**Pull request merged**
